### ISSUE TITLE
How to make it work also among computers not belonging to the same local network, which is the general interesting and useful case?

### ISSUE THREAD

**Issue by raphael10-collab** [fsteff/hyperpubsub#2]
Hi @fsteff !

I tested `example.js` with three computers: one PC and two laptops. All of them have Ubuntu 20.04 as O.S.

If all three computers are connected to the network through cable or through wireless, the messages are exchanged among them, according to the `example.js`.

If one of them is disconnected to the local network and is connected to the internet using the mobile phone's tethering, the messages are exchanged only between the other two computers, still connected to the local network through cable or wireless.

I tried with `hyperbeam` app :  https://github.com/mafintosh/hyperbeam
and it works fine between the pc connected to the local network through cable and a laptop connected to the internet through mobile phone's tethering, thus disconnected to the local network.

So it seems that the `example.js` works only among computers connected to the same local network.
Is it right? And how to make it work also among computers not belonging to the same local network, which is the general interesting and useful case?

**Comment by fsteff** [comment]
`example.js` uses the hyperspace simulator which AFAIK does not connect to the DHT to find peers. Like you tried in the other Ticket #1, you need a "real" hypespace server running. Please take a look at the [hyperspace docs](https://hypercore-protocol.org/guides/getting-started/hyperspace/).
